export const userExceptionMessage = {
  INVALID_ID: 'Invalide Id',
  USER_NOT_FOUND: 'User doesn\'t exit',
  ID_SAME: 'Id and friend_id same',
  FRIEND_ALREADY: 'User is already friend',
  REQUEST_SENT_ALREADY: 'Request is already sent.',
  ACCEPTED_ALREADY: 'Request accepted already.',
  REQUEST_NOT_SENT: 'Request has not been sent.',
  INVALID_QUERY: 'Search text empty',
  DELETE_FAILED: 'Failed to deleted the user.',
  FILE_REQUIRED: 'Image is required',
  UPDATE_FAILED: 'Update failed',
  PERMISSION_DENIED: 'Permission denied',
  USERNAME_LENGTH: 'Username should be 3 character long',
  USERNAME_REQUIRED: 'Username is required',
};
