export const postExceptionMessage = {
  NOT_FOUND: 'Post does\'t exits.',
  INVALID_ID: 'Post id invalid.',
  ID_REQUIRED: 'post_id is required.',
  CAPTION_REQUIRED: 'Caption is required.',
  POST_UNAVAIABLE: 'No post available',
  POST_INVALID: 'Values are missing',
  NAME_COMMENT_REQUIRED: 'Name and comment are required.',
  FILE_REQUIRED: 'Image is required.',
  POST_FALIED: 'Failed to create the post.',
  DELETE_FAILED: 'Failed to deleted the post.',
  PERMISSION_DENIED: 'Permisson Denied',
  NO_OF_POST_NUMBER: ' noOfPosts should be a number',
  NO_OF_POST_REQUIRED: ' noOfPosts is required',
  PAGE_REQUIRED: 'page is required',
  COMMENT_REQUIRED:'comment is required',
};
